config/routes.rb
Voyteam::Application.routes.draw do
  get 'shared' => 'tasks#my_tasks'
  post 'shared_new' => 'tasks#shared_new'

  resources :tasks do

    resources :users do
      collection do
        post 'share'
      end
    end
  end

  resources :comments

  root "home#index"
  devise_for :users

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :task
	belongs_to :user, :foreign_key => "author_id"
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :comments
	belongs_to :user, :foreign_key => "author_id"
end

app/models/tasks_users.rb
class TasksUsers < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :tasks
  has_many :comments
  has_many :tags, as: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.author_id = current_user.id
		if @comment.valid?
			@comment.save
			redirect_to :back
		else
			redirect_to :back
		end
	end

	private

	def comment_params
	  params.require(:comment).permit(:text, :task_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@user = User.new
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where('author_id = ?', current_user.id)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comment = Comment.new
    @comments = @task.comments
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.author_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  def my_tasks
    @user = User.find_by_id(current_user.id)
    @tasks = @user.tasks
    @data = @tasks.last.created_at
    @tasks.inspect
  end


  def shared_new
    @date = params[:date].to_datetime
    @tasks =current_user.tasks
    @task = @tasks.last.created_at
    puts @date.to_i
    puts @task.to_i
    if @task.to_i > @date.to_i
      @new = @tasks.last
    else
      @new = nil
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :author_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def share
    	@task = TasksUsers.new
	    	@task.task_id = params[:task_id]
	    	@task.user_id = params[:user_id]
    	@task.save
    	redirect_to :back
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
kkkkkkkk

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task Tracker</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<%if current_user%>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Task Tracker</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "My Tasks", tasks_path %></li>
            <li><%= link_to "Shared Tasks", '/shared' %></li>
            <li class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        Its a best task tracker for testtask on Teamvoy. Good Luck and Have Fun! 
      </div>
    </div>
  </div>
<%else%>
    <div class="jumbotron">
      <h1>Welcome, new user!</h1>
      <p class="lead">
        You must sign in or sign up before you can access our super sweet,
        top secret content.
      </p>
      <div class="row-fluid">
        <div class="span6">
          <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
        </div>
        <div class="span6">
          <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
        </div>
      </div>
      <%= yield %>
    </div>
<%end%>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/my_tasks.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
    </tr>
  </thead>
   <div id="show" align="center"></div>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%=l task.created_at %></td>
        <td><%= task.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<input type="hidden" name="mes" value="<%= @data %>" id="mes">

<script>
    $(document).ready(
            function() {
                setInterval(function() {
                  var date = $('#mes').val();
                    $.ajax({
                      type: "POST",
                      url: "/shared_new",
                      data: {date: date},
                        success: function(data,e){
                        console.log(data)
                        console.log(e)
                        if(this){
                           location.reload();

                              }
                         }
                       });

                }, 10000);
            });
</script>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @task.description %></dd>
</dl>

<div class="form-actions">
<%if @task.author_id == current_user.id %>
 <%= link_to t('.share', :default => t("helpers.links.share")),
              task_users_path(@task), :class => 'btn btn-large' %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<%else%>
<h2>Leave your comment and help your mates</h2> 
<%end%>
</div>


<%@comments.each do |c|%>
  <dl class="dl-horizontal">
    Message from <%= c.user.email %> </br>
    Text: </br>
    <%= c.text %>
  </dl>
<% end %>

<%= form_for @comment, method: :post, html: { role: "form", :multipart => true } do |f| %>
  <div class="form-group"></div>
  <%= f.label :text %>
  <%= f.text_area :text, class: "form-control" %>
  <input name="[comment][task_id]" type="hidden" value="<%= @task.id %>"></input>
  <div class="form-group"></div>
  <%= f.submit 'Add Comment', class: "btn btn-small" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %> 
<%=	user.email %>
<%= button_to 'Share to', share_task_users_path(:user_id => user.id), method: :post %>
<%end%>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>